#!/usr/bin/env bash
#
# monitor_qnap : mato [10-oct-2017]
#
# Check on a QNAP NAS appliance via SMTP
#

usage()
{
	echo "usage: ${0##*/} [<arg>...] host" >&2
	echo >&2
	echo "where: host -- QNAP server network name / address" >&2
	echo >&2
	echo "       --all       -- get all available metrics" >&2
	echo "       --cpu       -- get all cpu-* metrics" >&2
	echo "       --disk      -- get all disk-* metrics" >&2
	echo "       --interface -- get all interface-* metrics" >&2
	echo "       --memory    -- get all memory-* metrics" >&2
	echo "       --network   -- get all network-* metrics" >&2
	echo "       --system    -- get all system-* metrics" >&2
	echo "       --volume    -- get all volume-* metrics" >&2
	echo >&2
	echo "       -o|--output    -- output format (graphite, collectd)" >&2
	echo "       -V|--snmp      -- SNMP protocol version to use (1, 2c, 3); default: 3" >&2
	echo "       -A|--snmp-auth -- security name (v.3) or community name (v.1/2c)" >&2
	echo "       -v|--verbose   -- verbose output" >&2
	exit 100
}

getopt --test > /dev/null
if [ $? -ne 4 ]
then
	echo "ERROR: enhanced getopt from util-linux required" >&2
	exit 101
fi

OPTIONS="A:o:V:v?"
LONGOPTIONS="interval:,loop,output:,output-host:,snmp:,snmp-auth:,verbose"
LONGOPTIONS="$LONGOPTIONS,all,cpu,cpu-busy,cpu-temp"
LONGOPTIONS="$LONGOPTIONS,disk,disk-size,disk-status,disk-temp,fan,fan-speed"
LONGOPTIONS="$LONGOPTIONS,interface,interface-error,interface-rx,interface-tx"
LONGOPTIONS="$LONGOPTIONS,memory,memory-free,memory-total,memory-used"
LONGOPTIONS="$LONGOPTIONS,network,network-error,network-rx,network-tx,network-uptime"
LONGOPTIONS="$LONGOPTIONS,system,system-temp,system-uptime"
LONGOPTIONS="$LONGOPTIONS,volume,volume-free,volume-total,volume-used"

PARSED="$(getopt -o "$OPTIONS" -l "$LONGOPTIONS" -n "$0" -- "$@")"
[ $? -ne 0 ] && usage
eval set -- "$PARSED"

loop=false
protocol="3"
secstropt="-u"
verbose=0

while true
do
	case "$1" in
		# metrics options ..........................
		--all)
			do_all=1 ; shift ;;
		--cpu)
			do_cpu=1 ; shift ;;
		--cpu-busy)
			do_cpu_busy=1 ; shift ;;
		--cpu-temp)
			do_cpu_temp=1 ; shift ;;
		--disk)
			do_disk=1 ; shift ;;
		--disk-size)
			do_disk_size=1 ; shift ;;
		--disk-status)
			do_disk_status=1 ; shift ;;
		--disk-temp)
			do_disk_temp=1 ; shift ;;
		--fan)
			do_fan=1 ; shift ;;
		--fan-speed)
			do_fan_speed=1 ; shift ;;
		--interface)
			do_interface=1 ; shift ;;
		--interface-error)
			do_interface_error=1 ; shift ;;
		--interface-rx)
			do_interface_rx=1 ; shift ;;
		--interface-tx)
			do_interface_tx=1 ; shift ;;
		--memory)
			do_memory=1 ; shift ;;
		--memory-free)
			do_memory_free=1 ; shift ;;
		--memory-total)
			do_memory_total=1 ; shift ;;
		--memory-used)
			do_memory_used=1 ; shift ;;
		--network)
			do_network=1 ; shift ;;
		--network-error)
			do_network_error=1 ; shift ;;
		--network-rx)
			do_network_rx=1 ; shift ;;
		--network-tx)
			do_network_tx=1 ; shift ;;
		--network-uptime)
			do_network_uptime=1 ; shift ;;
		--system)
			do_system=1 ; shift ;;
		--system-temp)
			do_system_temp=1 ; shift ;;
		--system-uptime)
			do_system_uptime=1 ; shift ;;
		--volume)
			do_volume=1 ; shift ;;
		--volume-free)
			do_volume_free=1 ; shift ;;
		--volume-total)
			do_volume_total=1 ; shift ;;
		--volume-used)
			do_volume_used=1 ; shift ;;
		# general options ..........................
		--interval)
			interval="$2"
			shift 2 ;;
		--loop)
			loop=true
			shift ;;
		-o|--output)
			output="$2"
			case "$output" in
				graphite)	;;
				collectd)	;;
				*)
					echo "ERROR: wrong output format" >&2
					exit 100 ;;
			esac
			shift 2 ;;
		--output-host)
			output_host="$2"
			shift 2 ;;
		-V|--snmp)
			protocol="$2"
			case "$protocol" in
				3)
					secstropt="-u" ;;
				2c|1)
					secstropt="-c" ;;
				*)
					echo "ERROR: wrong protocol version" >&2
					exit 100 ;;
			esac
			shift 2 ;;
		-A|--snmp-auth)
			secstrval="$2"
			shift 2 ;;
		-v|--verbose)
			verbose=$((verbose+1))
			shift ;;
		-\?)
			usage ;;
		--)
			shift ; break ;;
		*)
			echo "ERROR!" >&2
			exit 123 ;;
	esac
done

[ $# -ne 1 ] && usage

host="$1"
[ -z "$output_host" ] && output_host="$host"
output_host="$(echo "$output_host" | sed -E 's/[^-_A-Za-z0-9]/_/g')"

# helper functions ...........................................................

_snmpget() {
	snmpget -v $protocol $secstropt "$secstrval" "$host" "$@"
}

_snmpgetval() {
	snmpget -v $protocol $secstropt "$secstrval" -Oqv "$host" "$@"
}

_snmpstatus() {
	snmpstatus -v $protocol $secstropt "$secstrval" "$host" "$@"
}

get_exp()	# return base 2 exponent matching unit passed in $1
{
	case "$1" in
		PB)	echo "50" ;;
		TB)	echo "40" ;;
		GB)	echo "30" ;;
		MB)	echo "20" ;;
		KB)	echo "10" ;;
		'')	echo "0" ;;
		*)	echo "ERROR: unknown unit '$1'" ;;
	esac
}

get_base_size()	# $1 - size including unit (e.g. "123 MB")
{
	local size="$(echo "$1" | sed -E 's/"([0-9.]+) ?.?B"/\1/')"
	local unit="$(echo "$1" | sed -E 's/"[0-9.]+ ?(.?B)"/\1/')"
	local exp="$(get_exp "$unit")"
	local base="$(echo "scale=0; $size*(2^$exp)" | bc -l)"
	echo "$base"
}

qnap_interval_to_seconds()	# $1 - datetime interval in the format days:hours:minutes:seconds
{
	echo "$1" | sed -E 's/([0-9]+):([0-9]+):([0-9]+):([0-9.]+)/\1*24*60*60 + \2*60*60 + \3*60 + \4/' | bc -l
}

export_metric()	# $1 - node, $2 - value
{
	case "$output" in
		graphite)
			local prefix=qnap
			echo "$prefix.$output_host.$1 $2 $(date '+%s')"
			;;
		collectd)
			local opts
			[ -n "$interval" ] && opts="$opts interval=$interval"
			local path="$(echo "$1" | sed -E -e 's/^([^.]+)\.(.+)$/qnap-\1\/\2/' -e 's/\./-/g')"
			echo "PUTVAL \"$output_host/$path\"$opts N:$2"
			;;
		*)
			echo "$output_host.$1 $2"
			;;
	esac
}

# --cpu ......................................................................

do_cpu_busy()
{
	local val="$(_snmpgetval .1.3.6.1.4.1.24681.1.2.1.0 | sed -E 's/"([0-9.]+) ?%"/\1/')"
	export_metric cpu.percent-busy "$val"
}

do_cpu_temp()
{
	local val="$(_snmpgetval .1.3.6.1.4.1.24681.1.2.5.0 | sed -E 's/"([0-9.]+) ?C.*/\1/')"
	export_metric cpu.temperature "$val"
}

# --disk .....................................................................

get_disk_count()
{
	echo "$(_snmpgetval .1.3.6.1.4.1.24681.1.2.10.0)"
}

get_disk_smart_info()	# $1 - disk number
{
	echo "$(_snmpgetval ".1.3.6.1.4.1.24681.1.2.11.1.7.$1" | sed -E 's/^"(.*)"$/\1/')"
}

get_disk_status()	# $1 - disk number
{
	echo "$(_snmpgetval ".1.3.6.1.4.1.24681.1.2.11.1.4.$1" | sed -E 's/^"(.*)"$/\1/')"
}

do_disk_status()
{
	for (( i=1; i <= "$(get_disk_count)"; i++ ))
	do
		export_metric "disk-$i.status" "$(get_disk_status "$i")"
	done
}

get_disk_size()	# $1 - disk number
{
	local str="$(_snmpgetval ".1.3.6.1.4.1.24681.1.2.11.1.6.$1")"
	echo "$(get_base_size "$str")"
}

do_disk_size()
{
	for (( i=1; i <= "$(get_disk_count)"; i++ ))
	do
		if [ "$(get_disk_smart_info "$i")" != '--' ]
		then
			export_metric "disk-$i.bytes-size" "$(get_disk_size "$i")"
		fi
	done
}

get_disk_temp()	# $1 - disk number
{
	local str="$(_snmpgetval ".1.3.6.1.4.1.24681.1.2.11.1.3.$1")"
	local val="$(echo "$str" | sed -E 's/"([0-9.]+) ?C.*/\1/')"
	echo "$val"
}

do_disk_temp()
{
	for (( i=1; i <= "$(get_disk_count)"; i++ ))
	do
		if [ "$(get_disk_smart_info "$i")" != '--' ]
		then
			export_metric "disk-$i.temperature" "$(get_disk_temp "$i")"
		fi
	done
}

# --fan ......................................................................

get_fan_count()
{
	echo "$(_snmpgetval .1.3.6.1.4.1.24681.1.2.14.0)"
}

get_fan_speed()	# $1 - fan number
{
	local str="$(_snmpgetval ".1.3.6.1.4.1.24681.1.2.15.1.3.$1")"
	local val="$(echo "$str" | sed -E 's/"([0-9]+) ?RPM"/\1/')"
	echo "$val"
}

do_fan_speed()
{
	for (( i=1; i <= "$(get_fan_count)"; i++ ))
	do
		export_metric "fan-$i.fanspeed" "$(get_fan_speed "$i")"
	done
}

# --interface ................................................................

get_interface_count()
{
	echo "$(_snmpgetval .1.3.6.1.4.1.24681.1.2.8.0)"
}

get_interface_packets_error()	# $1 - network interface number
{
	echo "$(_snmpgetval ".1.3.6.1.4.1.24681.1.2.9.1.5.$1")"
}

do_interface_packets_error()
{
	for (( i=1; i <= "$(get_interface_count)"; i++ ))
	do
		export_metric "interface-$i.packets.error" "$(get_interface_packets_error "$i")"
	done
}

get_interface_packets_rx()	# $1 - network interface number
{
	echo "$(_snmpgetval ".1.3.6.1.4.1.24681.1.2.9.1.3.$1")"
}

do_interface_packets_rx()
{
	for (( i=1; i <= "$(get_interface_count)"; i++ ))
	do
		export_metric "interface-$i.packets.rx" "$(get_interface_packets_rx "$i")"
	done
}

get_interface_packets_tx()	# $1 - network interface number
{
	echo "$(_snmpgetval ".1.3.6.1.4.1.24681.1.2.9.1.4.$1")"
}

do_interface_packets_tx()
{
	for (( i=1; i <= "$(get_interface_count)"; i++ ))
	do
		export_metric "interface-$i.packets.tx" "$(get_interface_packets_tx "$i")"
	done
}

# --memory ...................................................................

get_memory_free()
{
	local str="$(_snmpgetval .1.3.6.1.4.1.24681.1.2.3.0)"
	echo "$(get_base_size "$str")"
}

do_memory_free()
{
	export_metric memory.bytes-free "$(get_memory_free)"
}

get_memory_total()
{
	local str="$(_snmpgetval .1.3.6.1.4.1.24681.1.2.2.0)"
	echo "$(get_base_size "$str")"
}

do_memory_total()
{
	export_metric memory.bytes-total "$(get_memory_total)"
}

do_memory_used()
{
	local f="$(get_memory_free)"
	local t="$(get_memory_total)"
	local u="$(echo "scale=0; $t - $f" | bc -l)"
	local p="$(echo "scale=0; $u * 100 / $t" | bc -l)"
	export_metric memory.bytes-used "$u"
	export_metric memory.percent-used "$p"
}

# --network ..................................................................

do_network_packets_error()
{
	local -i c=0
	for (( i=1; i <= "$(get_interface_count)"; i++ ))
	do
		(( c += "$(get_interface_packets_error "$i")" ))
	done
	export_metric network.packets.error "$c"
}

do_network_packets_rx()
{
	local -i c=0
	for (( i=1; i <= "$(get_interface_count)"; i++ ))
	do
		(( c += "$(get_interface_packets_rx "$i")" ))
	done
	export_metric network.packets.rx "$c"
}

do_network_packets_tx()
{
	local -i c=0
	for (( i=1; i <= "$(get_interface_count)"; i++ ))
	do
		(( c += "$(get_interface_packets_tx "$i")" ))
	done
	export_metric network.packets.tx "$c"
}

do_network_uptime()
{
	local str="$(_snmpgetval .1.3.6.1.2.1.1.3.0)"
	local sec="$(qnap_interval_to_seconds "$str")"
	export_metric network.uptime "$sec"
}

# --system ...................................................................

do_system_temp()
{
	local str="$(_snmpgetval .1.3.6.1.4.1.24681.1.2.6.0)"
	local val="$(echo "$str" | sed -E 's/"([0-9.]+) ?C.*/\1/')"
	export_metric system.temperature "$val"
}

do_system_uptime()
{
	local str="$(_snmpgetval .1.3.6.1.2.1.25.1.1.0)"
	local sec="$(qnap_interval_to_seconds "$str")"
	export_metric system.uptime "$sec"
}

# --volume ...................................................................

get_volume_count()
{
	echo "$(_snmpgetval .1.3.6.1.4.1.24681.1.2.16.0)"
}

get_volume_status()	# $1 - volume number
{
	echo "$(_snmpgetval ".1.3.6.1.4.1.24681.1.2.17.1.6.$1" | sed -E 's/^"(.*)"$/\1/')"
}

get_volume_free()	# $1 - volume number
{
	local str="$(_snmpgetval ".1.3.6.1.4.1.24681.1.2.17.1.5.$1")"
	echo "$(get_base_size "$str")"
}

do_volume_free()
{
	for (( i=1; i <= "$(get_volume_count)"; i++ ))
	do
		if [ "$(get_volume_status "$i")" = 'Ready' ]
		then
			export_metric "volume-$i.bytes-free" "$(get_volume_free "$i")"
		fi
	done
}

get_volume_total()	# $1 - volume number
{
	local str="$(_snmpgetval ".1.3.6.1.4.1.24681.1.2.17.1.4.$1")"
	echo "$(get_base_size "$str")"
}

do_volume_total()
{
	for (( i=1; i <= "$(get_volume_count)"; i++ ))
	do
		if [ "$(get_volume_status "$i")" = 'Ready' ]
		then
			export_metric "volume-$i.bytes-total" "$(get_volume_total "$i")"
		fi
	done
}

do_volume_used()
{
	for (( i=1; i <= "$(get_volume_count)"; i++ ))
	do
		if [ "$(get_volume_status "$i")" = 'Ready' ]
		then
			local f="$(get_volume_free "$i")"
			local t="$(get_volume_total "$i")"
			local u="$(echo "scale=0; $t - $f" | bc -l)"
			local p="$(echo "scale=0; $u * 100 / $t" | bc -l)"
			export_metric "volume-$i.bytes-used" "$u"
			export_metric "volume-$i.percent-used" "$p"
		fi
	done
}

# main code ..................................................................

run_once()
{
	# Check if the target is reachable and answers to SNMP
	status="$(_snmpstatus 2>&1)"
	if [ $? -ne 0 ]
	then
		echo "$status" >&2
		exit 1
	fi

	# Get all metrics as requested ...
	[ -n "$do_cpu_busy" -o -n "$do_cpu" -o -n "$do_all" ] && do_cpu_busy
	[ -n "$do_cpu_temp" -o -n "$do_cpu" -o -n "$do_all" ] && do_cpu_temp
	[ -n "$do_disk_size" -o -n "$do_disk" -o -n "$do_all" ] && do_disk_size
	[ -n "$do_disk_status" -o -n "$do_disk" -o -n "$do_all" ] && do_disk_status
	[ -n "$do_disk_temp" -o -n "$do_disk" -o -n "$do_all" ] && do_disk_temp
	[ -n "$do_fan_speed" -o -n "$do_fan" -o -n "$do_all" ] && do_fan_speed
	[ -n "$do_interface_error" -o -n "$do_interface" -o -n "$do_all" ] && do_interface_packets_error
	[ -n "$do_interface_rx" -o -n "$do_interface" -o -n "$do_all" ] && do_interface_packets_rx
	[ -n "$do_interface_tx" -o -n "$do_interface" -o -n "$do_all" ] && do_interface_packets_tx
	[ -n "$do_memory_free" -o -n "$do_memory" -o -n "$do_all" ] && do_memory_free
	[ -n "$do_memory_total" -o -n "$do_memory" -o -n "$do_all" ] && do_memory_total
	[ -n "$do_memory_used" -o -n "$do_memory" -o -n "$do_all" ] && do_memory_used
	[ -n "$do_network_error" -o -n "$do_network" -o -n "$do_all" ] && do_network_packets_error
	[ -n "$do_network_rx" -o -n "$do_network" -o -n "$do_all" ] && do_network_packets_rx
	[ -n "$do_network_tx" -o -n "$do_network" -o -n "$do_all" ] && do_network_packets_tx
	[ -n "$do_network_uptime" -o -n "$do_network" -o -n "$do_all" ] && do_network_uptime
	[ -n "$do_system_temp" -o -n "$do_system" -o -n "$do_all" ] && do_system_temp
	[ -n "$do_system_uptime" -o -n "$do_system" -o -n "$do_all" ] && do_system_uptime
	[ -n "$do_volume_free" -o -n "$do_volume" -o -n "$do_all" ] && do_volume_free
	[ -n "$do_volume_total" -o -n "$do_volume" -o -n "$do_all" ] && do_volume_total
	[ -n "$do_volume_used" -o -n "$do_volume" -o -n "$do_all" ] && do_volume_used
}

if $loop
then
	if [ "$output" = "collectd" ]
	then
		interval="${interval:-${COLLECTD_INTERVAL:-60}}"
	else
		interval="${interval:-60}"
	fi

	while true
	do
		tick="$(date '+%s')"
		echo "# $(date +'%Y-%m-%d %T')"
		run_once

		while (( "$(date '+%s')" < "$tick" + "$interval" ))
		do
			sleep 1
		done
	done
else
	run_once
fi

exit 0

# the end
